language: php

php:
 - 5.3
 - 5.4
 - 5.5
 - 5.6
# - 7.0 // Will be available very soon

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - composer self-update

install:
  - composer install --prefer-dist

script:
  - vendor/bin/phing build
