language: php

matrix:
  include:
   - 5.3
   - 5.4
   - 5.5
   - 5.6
     env: SCRUTINIZER_REPORT=true
   - 7.0

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - composer self-update

install:
  - composer install --prefer-dist

script:
  - vendor/bin/phing build
  - bin/permcheck -c permcheck.example.xml

after_script: >
  [ "$SCRUTINIZER_REPORT" = true ]
  && wget https://scrutinizer-ci.com/ocular.phar
  && php ocular.phar code-coverage:upload --format=php-clover coverage.clover
